version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings
    columns:

     - name: listing_id
       description: primary key for the listing
       tests:
         - unique
         - not_null

     - name: host_id
       description: The hosts id, references the hosts table
       tests:
         - not_null
         - relationships:
             to: ref('dim_hosts_cleansed')
             field: host_id

     - name: room_type
       description: Type of the room apartment
       tests:
         - accepted_values:
             values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
                      
